name: Notify Upcoming Deadlines

on:
  schedule:
    # 1時間ごと
    - cron: '*/60 * * * *'
  workflow_dispatch: # 手動実行も可能にする

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      ICS_URL: ${{ secrets.ICS_URL }} # GitHub Secretsに設定したICSのURL
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # GitHub Secretsに設定したDiscordのWebhook URL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 適切なPythonバージョンを指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar pytz

      - name: Restore cache for notified events
        uses: actions/cache@v4
        id: cache-notified-events # ステップにIDを付与して、後で出力（cache-hit）を参照できるようにする
        with:
          path: notified.json # キャッシュするファイルのパス
          key: ${{ runner.os }}-notified-events # キャッシュキー。OSが変わることは少ないが、念のため含める

      - name: Run script to check and notify deadlines
        run: python LMS_assignment_notify.py 


